"""Add confidence score

Revision ID: bded9b324737
Revises: 3ef1385dc041
Create Date: 2026-07-11 11:46:46.950978

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bded9b324737'
down_revision: Union[str, Sequence[str], None] = '3ef1385dc041'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('query_logs', sa.Column('confidence_score', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('query_logs', 'confidence_score')
    # ### end Alembic commands ###
